### ISSUE TITLE
User Passwords in response

### ISSUE THREAD

**Issue by Alkandari-Y** [Mariam-HA/food-recipes-backend#19]
You currently have an `exposed endpoint` returning all user info including `hashed passwords` which poses a `security risk`.

Currently this is what the response looks like:
```json
[
    {
        "_id": "64ab7acd070eac731a827a39",
        "email": "admin@test.com",
        "username": "admin",
        "password": "$2b$10$B8Wn9ZuNiWvdAmXzT755a.tm88ml/4X6nkKhE6jN59mVJJmpSEbfu",
        "userImage": "media/1688959693763e68.jpg",
        "recipes": [],
        "reviews": [],
        "createdAt": "2023-07-10T03:28:13.831Z",
        "updatedAt": "2023-07-10T03:28:13.831Z",
        "__v": 0
    }
]
```
I know that this is a learning project, but I have to alert you that this kind of looseness with data exposure poses a risk to users and to you.

Always be alert and on guard when dealing with user data. 

In the `getUser` controller found in `auth.controllers`, use the `select` method to ignore the passwords. Use `MongoDbCompass` to inspect passwords are being saved and hashed properly.

**Comment by Nouftalajmi** [comment]
done
