### ISSUE TITLE
Delete Category

### ISSUE THREAD

**Issue by Alkandari-Y** [Mariam-HA/food-recipes-backend#34]
Since the `Categories` are shared by all users, should we permit the ability for logged in users to potentially delete a `category`? What if someone is using that `category`? Can it still be deleted?

These are questions that come to mind when I see the `deleteCat` controller.

Additionally, the `deleteCat` controller will always return 204, even if the `category` doesnt exist to begin with. We can use a `router.param` middleware to help with this, since we are using similar logic with the `getCatById` controller.

**Comment by Nouftalajmi** [comment]
done
